FROM node:20-alpine

RUN npm install -g pnpm

WORKDIR /app

COPY package.json ./
RUN pnpm install
COPY . .

ARG RAILWAY_GIT_COMMIT_SHA
ARG RAILWAY_ENVIRONMENT_NAME
ARG RAILWAY_PROJECT_NAME
ARG RAILWAY_SERVICE_NAME
ARG VITE_ENABLE_GAME_TEST_API

RUN pnpm build

EXPOSE 4173
CMD ["pnpm", "start"]
